export const projects = [
  {
    title: 'Code Editor',
    description: "Using React, Node.js, Codemirror you'll learn how to build a code Editor like codepen Application - from start to finish. The App is called Integrated development environmentand it is a simple xml, css and javaScript code Editor that allows  devloper to build a simple web app using xml, css and javaScript .",
    image: '/images/1.png',
    tags: ['React', 'Node', 'Codemirror'],
    source: 'https://github.com/ishukhan/CodeEditor',
    visit: 'https://code-editor-d9b18.web.app/',
    id: 0,
  },
  // {
  //   title: 'E-Commerce',
  //   description: 'IN PROCESS',
  //   // description:"While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
  //   // image: '/images/2.png',
  //   tags: ['React', 'JavaScript'],
  //   source: 'https://github.com/ishukhan/CodeEditor',
  //   visit: 'https://google.com',
  //   id: 1,
  // },
  // {
  //   title: 'WebRTC App',
  //   description: 'IN PROCESS',
  //   // description: "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
  //   // image: '/images/3.jpg',
  //   tags: ['React', 'WebRTC'],
  //   source: 'https://google.com',
  //   visit: 'https://google.com',
  //   id: 2,
  // },
  // {
  //   title: 'Unichat',
  //   description: 'IN PROCESS',
  //   // description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
  //   // image: '/images/4.jpg',
  //   tags: ['React', 'ChatEngine', 'Firebase'],
  //   source: 'https://google.com',
  //   visit: 'https://google.com',
  //   id: 3,
  // },
];

export const TimeLineData = [
  { year: 2018, text: 'Started my journey.', },
  { year: 2019, text: 'Learn new things in tech world.', },
  { year: 2020, text: 'Create Beginner level projects.', },
  { year: 2021, text: 'I have Completed My Bachlor.', },
  { year: 2022, text: 'Worked as a Data-Entry Operator.', },
  { year: 2023, text: 'Currently I am learning new technology.', },
];